# Generated by Django 2.2.3 on 2020-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subsection', models.CharField(max_length=15, verbose_name='分段')),
                ('sec_num', models.CharField(max_length=15, verbose_name='段内人数')),
                ('sum', models.CharField(max_length=15, verbose_name='累计人数')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '黑龙江省高考理科成绩一分一段表',
            },
        ),
    ]
